services:
  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVER_URL=http://auth:3001
      - EVENT_SERVER_URL=http://event:3002
    depends_on:
      - auth
      - event

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://auth-db:27017/auth
    depends_on:
      - auth-db

  auth-db:
    image: mongo
    container_name: auth-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - auth-db-data:/data/db

  event:
    build: ./apps/event
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://event-db:27017/event
    depends_on:
      - event-db

  event-db:
    image: mongo
    container_name: event-db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - event-db-data:/data/db

volumes:
  auth-db-data:
  event-db-data: